
name: Cypress Tests and Cloud Run Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest
    # needs: cypress

    env:
      PROJECT_ID: inbound-pattern-422518-k7
      APP_NAME: groupproject-frontend
      SER_NAME: groupproject-frontend
      REGION: europe-west1
      SER_PORT: 8081

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
    

      - name: Build Image, Push to Registry, Deploy to Cloud Run
        run: |
          export IMAGE_NAME=europe-west1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.APP_NAME }}/${{ env.SER_NAME }}:$GITHUB_SHA
          echo '${{ secrets.KEY_FILE }}' | jq '.' > client-secret.json
          gcloud auth activate-service-account individual-account@inbound-pattern-422518-k7.iam.gserviceaccount.com --key-file client-secret.json
          gcloud config set project ${{ env.PROJECT_ID }}
          gcloud auth configure-docker europe-west1-docker.pkg.dev
          export DOCKER_BUILDKIT=0
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
          gcloud run deploy ${{ env.SER_NAME }} --image $IMAGE_NAME --port ${{ env.SER_PORT }} --region ${{ env.REGION }} --cpu=1 --memory=1Gi --timeout=3000 --allow-unauthenticated || true
        env:
          KEY_FILE: ${{ secrets.KEY_FILE }}




  owasp-scan:
    name: OWASP Scan
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          token: ${{ secrets.GITHUB }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://groupproject-frontend-hlfxsphkja-ew.a.run.app'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'






